name: .NET Core

on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Install dependencies
      run: dotnet restore ./ApiOnEndpoints.sln
    - name: Build
      run: dotnet build ./ApiOnEndpoints.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./ApiOnEndpoints.sln --no-restore --verbosity normal
